### PR TITLE
Part 5 tasks

### PR DESCRIPTION
**Pull request by loshuyen**
羅書硯
http://52.38.139.195:8000/
http://52.38.139.195:8000/attraction/10
http://52.38.139.195:8000/booking

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
- Your pages always call User Auth API twice after loading.
- Circles in the bottom of image slider are broken.

**Comment by loshuyen** [comment]
> * Your pages always call User Auth API twice after loading.
This issue is fixed. 

> * Circles in the bottom of image slider are broken.
I do not see any broken of these circles. Could you please give me a screenshot or further information? Thanks.
Screenshot 2024-06-25 at 6 14 16 PM

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. OK.
2. I think it's due to visible scroll bar. Different operating system and browser may render scroll bar in different way, try to hide scroll bar totally.
52 38 139 195_8000_attraction_2

**Comment by loshuyen** [comment]
I modified the css settings to hide the scrollbar. If there's still any issues, please let me know. Thanks.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
