### PR TITLE
Part 2 task

### PR DESCRIPTION
**Pull request by loshuyen**
羅書硯
http://52.38.139.195:8000

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Layout width exceeds screen width.
未命名-6

**Comment by loshuyen** [comment]
@cwpeng I can not reproduce this issue like you did.

**Comment by loshuyen** [comment]
@cwpeng I can not reproduce this issue like you did.
Screenshot 2024-06-06 at 10 14 24 AM
Screenshot 2024-06-06 at 10 54 30 AM

**Comment by cwpeng** [comment]
Try to drag-drop your page horizontally, check if your layout can be scrolled.

**Comment by loshuyen** [comment]
Yes, I did try. The issue didn't show up.

**Comment by loshuyen** [comment]
> Try to drag-drop your page horizontally, check if your layout can be scrolled.

@cwpeng  Yes, I did try. The issue didn't show up.

**Review by cwpeng — APPROVED** [review]
OK. I accept that.

I think it's because 100vw will count scrollbar width, so that if we have scrollbar in the right side, your layout will exceed slightly. If you think it worth your attention, try 100% for layout width.

**Comment by loshuyen** [comment]
> OK. I accept that.
> 
> I think it's because 100vw will count scrollbar width, so that if we have scrollbar in the right side, your layout will exceed slightly. If you think it worth your attention, try 100% for layout width.

I also tried with the browser in another PC. The layout was still not scrollable. I will keep digging in this problem. Thanks for the feedback.

**Pull request merged**
